base_url: "https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/ensostuff/detrend.nino34.ascii.txt"
title: "El Ni単o-Southern Oscillation (ENSO): El Ni単o and La Ni単a Events"
description: Monthly analysis of the El Ni単o-Southern Oscillation (ENSO) cycle

tags:
  - climate hazards
  - climate-weather
  - el nino-el nina
  - hxl

hxl_tags:
  "date": "#date+reported"
  "TOTAL": "#value+total"
  "ClimAdjust": "#value+climadjust"
  "ANOM": "#value+anom"
  "ANOM_trimester": "#value+anom+trimester"
  "ANOM_trimester_round": "#value+anom+trimester+rounded"
  "phase_trimester": "#meta+phase+trimester"
  "phase_event": "#meta+phase+event"
